server:
  port: 6001
spring:
  application:
    name: gateway


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6543/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}  #固定端口
  #    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${randomServerPort.value[7000,7005]}}  #随机端口
      #instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
      lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
      lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
      status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/document.html
zuul:
  routes: #固定端口
    user:
      path: /user-api/**
      serviceId: user
    article:
      path: /article-api/**
      serviceId: article





